/**
 * Page object for the Table of Contents block inside the WordPress editor.
 *
 * IFRAME BOUNDARY -- the thing to get right here.
 * The block declares apiVersion 3, which makes WordPress render the editor
 * canvas inside an <iframe name="editor-canvas">. Block content therefore
 * lives in `editor.canvas`, while the inspector sidebar lives in the top-level
 * `page`. Querying block markup on `page` silently finds nothing; querying the
 * sidebar on `editor.canvas` does the same. Every method below is on one side
 * of that line, deliberately.
 */

import type { Locator, Page } from '@playwright/test';
import type { Editor } from '@wordpress/e2e-test-utils-playwright';
import { BLOCK, EDITOR, INSPECTOR_ROOT, TABS, type TabLabel } from './selectors';

export class TocEditor {
	constructor(
		private readonly page: Page,
		private readonly editor: Editor
	) {}

	// -----------------------------------------------------------------
	// Canvas (inside the iframe)
	// -----------------------------------------------------------------

	/**
	 * Inserts the block via the editor's own insertion API.
	 *
	 * Deliberately NOT editor.setContent() with hand-written block markup.
	 * The `blockId` attribute is generated by the block's own mount effect and
	 * the PHP renderer builds its container class from it -- pasting serialized
	 * markup without one produces a block that looks fine in the editor and
	 * renders subtly wrong on the frontend.
	 */
	async insert() {
		await this.editor.insertBlock( { name: BLOCK.name } );
	}

	/** Inserts a heading after whatever is currently selected. */
	async insertHeading( content: string, level = 2 ) {
		await this.editor.insertBlock( {
			name: 'core/heading',
			attributes: { content, level },
		} );
	}

	container(): Locator {
		return this.editor.canvas.locator( EDITOR.container );
	}

	/** The block as the editor exposes it -- used to select it by clicking. */
	block(): Locator {
		return this.editor.canvas.getByRole( 'document', {
			name: `Block: ${ BLOCK.title }`,
		} );
	}

	links(): Locator {
		return this.container().locator( EDITOR.links );
	}

	listItems(): Locator {
		return this.container().locator( EDITOR.listItems );
	}

	/** Visible text of every TOC entry, in document order. */
	async linkTexts(): Promise< string[] > {
		return ( await this.links().allInnerTexts() ).map( ( t ) => t.trim() );
	}

	/**
	 * Finds the <li> whose own link is `parentText`, then looks for a nested
	 * link inside it. This distinguishes real nesting from mere ordering: a
	 * flat list would put the child after the parent, not within it.
	 */
	nestedLinkUnder( parentText: string, childText: string ): Locator {
		return this.container()
			.locator( 'li' )
			.filter( { has: this.page.locator( `a:text-is("${ parentText }")` ) } )
			.first()
			.locator( `a:text-is("${ childText }")` );
	}

	// -----------------------------------------------------------------
	// Inspector sidebar (top-level page, outside the iframe)
	// -----------------------------------------------------------------

	/** Selects the block and opens its settings sidebar. */
	async openInspector() {
		await this.block().click();
		await this.editor.openDocumentSettingsSidebar();
	}

	inspector(): Locator {
		return this.page.locator( INSPECTOR_ROOT );
	}

	/** Tab button located by CSS class -- identity, independent of label text. */
	tabButton( label: TabLabel ): Locator {
		const tab = TABS.find( ( t ) => t.label === label )!;
		return this.page.locator( tab.button );
	}

	/**
	 * The same button located by ARIA role and accessible name. Kept separate
	 * from tabButton() on purpose: asserting both proves the tab is identifiable
	 * to assistive technology as well as to CSS, and a change that breaks only
	 * one of them still fails.
	 */
	tabByRole( label: TabLabel ): Locator {
		return this.inspector().getByRole( 'tab', { name: label, exact: true } );
	}

	/**
	 * Panel content for a tab.
	 *
	 * Two things look wrong here and are not. The class has no separator before
	 * the tab name (`eb-tab-controlsgeneral`), and only the ACTIVE tab's panel
	 * exists in the DOM at all -- inactive panels are unmounted, not hidden.
	 * So this locator legitimately resolves to zero elements for any tab that
	 * is not currently selected.
	 */
	tabPanel( label: TabLabel ): Locator {
		const tab = TABS.find( ( t ) => t.label === label )!;
		return this.page.locator( tab.panel );
	}

	async openTab( label: TabLabel ) {
		await this.tabButton( label ).click();
	}

	/**
	 * A PanelBody by its visible title. PanelBody renders its title as a
	 * button, which is how we tell a real settings section from arbitrary text
	 * that happens to match.
	 */
	panel( title: string ): Locator {
		return this.inspector().getByRole( 'button', { name: title, exact: true } );
	}
}
