/**
 * Page object for the Table of Contents block inside the WordPress editor.
 *
 * IFRAME BOUNDARY -- the thing to get right here.
 * The block declares apiVersion 3, which makes WordPress render the editor
 * canvas inside an <iframe name="editor-canvas">. Block content therefore
 * lives in `editor.canvas`, while the inspector sidebar lives in the top-level
 * `page`. Querying block markup on `page` silently finds nothing; querying the
 * sidebar on `editor.canvas` does the same. Every method below is on one side
 * of that line, deliberately.
 */

import type { Locator, Page } from '@playwright/test';
import type { Editor } from '@wordpress/e2e-test-utils-playwright';
import { BLOCK, EDITOR, INSPECTOR_ROOT, TABS, type TabLabel } from './selectors';

/**
 * The slice of `core/block-editor`'s block shape attributes()/setAttributes()
 * need. `window.wp` itself is typed `any` (declared by
 * @wordpress/e2e-test-utils-playwright globally, which a stronger local type
 * can't override via declaration merging), so callbacks passed to
 * page.evaluate() type their own return value explicitly instead.
 */
interface EditorBlock {
	clientId: string;
	name: string;
	attributes: Record< string, unknown >;
}

export class TocEditor {
	constructor(
		private readonly page: Page,
		private readonly editor: Editor
	) {}

	// -----------------------------------------------------------------
	// Canvas (inside the iframe)
	// -----------------------------------------------------------------

	/**
	 * Inserts the block via the editor's own insertion API.
	 *
	 * Deliberately NOT editor.setContent() with hand-written block markup.
	 * The `blockId` attribute is generated by the block's own mount effect and
	 * the PHP renderer builds its container class from it -- pasting serialized
	 * markup without one produces a block that looks fine in the editor and
	 * renders subtly wrong on the frontend.
	 */
	async insert() {
		await this.editor.insertBlock( { name: BLOCK.name } );
	}

	/** Inserts a heading after whatever is currently selected. */
	async insertHeading( content: string, level = 2 ) {
		await this.editor.insertBlock( {
			name: 'core/heading',
			attributes: { content, level },
		} );
	}

	container(): Locator {
		return this.editor.canvas.locator( EDITOR.container );
	}

	/** The block as the editor exposes it -- used to select it by clicking. */
	block(): Locator {
		return this.editor.canvas.getByRole( 'document', {
			name: `Block: ${ BLOCK.title }`,
		} );
	}

	links(): Locator {
		return this.container().locator( EDITOR.links );
	}

	listItems(): Locator {
		return this.container().locator( EDITOR.listItems );
	}

	/** The outermost entry list -- first in DOM order, since the editor's own
	 *  list builder writes the top-level `<${listStyle}>` before any nested
	 *  ones. Mirrors TocFrontend.list(). */
	list(): Locator {
		return this.container().locator( EDITOR.list ).first();
	}

	/** 'UL' or 'OL'. */
	async listTagName(): Promise< string > {
		return this.list().evaluate( ( el ) => el.tagName );
	}

	/** The container's own classes -- editor-side equivalent of
	 *  TocFrontend.containerClassList(), used for preset/collapsible-state
	 *  assertions that need to hold in both places. */
	async containerClassList(): Promise< string[] > {
		const raw = await this.container().getAttribute( 'class' );
		return raw ? raw.split( /\s+/ ).filter( Boolean ) : [];
	}

	/** Visible text of every TOC entry, in document order. */
	async linkTexts(): Promise< string[] > {
		return ( await this.links().allInnerTexts() ).map( ( t ) => t.trim() );
	}

	/**
	 * Finds the <li> whose own link is `parentText`, then looks for a nested
	 * link inside it. This distinguishes real nesting from mere ordering: a
	 * flat list would put the child after the parent, not within it.
	 */
	nestedLinkUnder( parentText: string, childText: string ): Locator {
		return this.container()
			.locator( 'li' )
			.filter( { has: this.page.locator( `a:text-is("${ parentText }")` ) } )
			.first()
			.locator( `a:text-is("${ childText }")` );
	}

	/** The block's own title element -- used for the D4 collapsible-title
	 *  click. Renders as a RichText div with className "eb-toc-title", the
	 *  same class EDITOR.title already names. */
	title(): Locator {
		return this.container().locator( EDITOR.title );
	}

	/**
	 * The item-collapse chevron for one entry, if it has one.
	 *
	 * Two scopings matter here, for different reasons. `:scope > a` on the
	 * filter is what makes this the entry's OWN <li> rather than an
	 * ancestor's -- `has: a:text-is(...)` without it also matches any
	 * ancestor li, since a parent contains its children's links as
	 * descendants. `:scope > svg` on the result is what makes this the
	 * entry's OWN chevron rather than a nested descendant's.
	 */
	collapseToggle( entryText: string ): Locator {
		return this.container()
			.locator( 'li' )
			.filter( { has: this.page.locator( `:scope > a:text-is("${ entryText }")` ) } )
			.locator( ':scope > svg' );
	}

	// -----------------------------------------------------------------
	// Attribute access (bypasses the UI -- for REST-fixture-equivalent state
	// on a block that must be authored through the editor, and for
	// round-trip assertions after a UI-driven change)
	// -----------------------------------------------------------------

	/**
	 * Reads this block's current attributes straight from the editor's data
	 * store. Used both to assert "the control wrote the right attribute" and
	 * for the publish/reload round-trip check.
	 */
	async attributes(): Promise< Record< string, unknown > > {
		return this.page.evaluate( ( blockName: string ) => {
			const blocks = window.wp.data
				.select( 'core/block-editor' )
				.getBlocks() as EditorBlock[];
			const block = blocks.find( ( b ) => b.name === blockName );
			return block?.attributes ?? {};
		}, BLOCK.name );
	}

	/**
	 * Writes attributes directly through `updateBlockAttributes`, bypassing
	 * the inspector UI. Deliberately NOT editor.setContent() with hand-written
	 * markup -- see the comment on insert(): blockId and blockMeta come from
	 * the block's own mount effect, and pasted markup without them renders
	 * subtly wrong on the frontend. This is the equivalent capability for a
	 * block that (unlike a REST fixture) has already been mounted in a real
	 * editor session, e.g. the sticky position:fixed test, which needs
	 * blockMeta and therefore cannot be a REST fixture at all.
	 */
	async setAttributes( partial: Record< string, unknown > ) {
		await this.page.evaluate(
			( [ blockName, attrs ]: [ string, Record< string, unknown > ] ) => {
				const blocks = window.wp.data
					.select( 'core/block-editor' )
					.getBlocks() as EditorBlock[];
				const block = blocks.find( ( b ) => b.name === blockName );
				if ( ! block ) {
					throw new Error( `${ blockName } is not in the editor.` );
				}
				window.wp.data
					.dispatch( 'core/block-editor' )
					.updateBlockAttributes( block.clientId, attrs );
			},
			[ BLOCK.name, partial ] as [ string, Record< string, unknown > ]
		);
	}

	// -----------------------------------------------------------------
	// Inspector sidebar (top-level page, outside the iframe)
	// -----------------------------------------------------------------

	/** Selects the block and opens its settings sidebar. */
	async openInspector() {
		await this.block().click();
		await this.editor.openDocumentSettingsSidebar();
	}

	inspector(): Locator {
		return this.page.locator( INSPECTOR_ROOT );
	}

	/** Tab button located by CSS class -- identity, independent of label text. */
	tabButton( label: TabLabel ): Locator {
		const tab = TABS.find( ( t ) => t.label === label )!;
		return this.page.locator( tab.button );
	}

	/**
	 * The same button located by ARIA role and accessible name. Kept separate
	 * from tabButton() on purpose: asserting both proves the tab is identifiable
	 * to assistive technology as well as to CSS, and a change that breaks only
	 * one of them still fails.
	 */
	tabByRole( label: TabLabel ): Locator {
		return this.inspector().getByRole( 'tab', { name: label, exact: true } );
	}

	/**
	 * Panel content for a tab.
	 *
	 * Two things look wrong here and are not. The class has no separator before
	 * the tab name (`eb-tab-controlsgeneral`), and only the ACTIVE tab's panel
	 * exists in the DOM at all -- inactive panels are unmounted, not hidden.
	 * So this locator legitimately resolves to zero elements for any tab that
	 * is not currently selected.
	 */
	tabPanel( label: TabLabel ): Locator {
		const tab = TABS.find( ( t ) => t.label === label )!;
		return this.page.locator( tab.panel );
	}

	async openTab( label: TabLabel ) {
		await this.tabButton( label ).click();
	}

	/**
	 * A PanelBody by its visible title. PanelBody renders its title as a
	 * button, which is how we tell a real settings section from arbitrary text
	 * that happens to match.
	 */
	panel( title: string ): Locator {
		return this.inspector().getByRole( 'button', { name: title, exact: true } );
	}

	/**
	 * Opens a PanelBody that starts collapsed -- Title and Scroll both render
	 * with `initialOpen: false`, unlike Content Settings. A no-op if it is
	 * already open, so callers don't need to track state themselves.
	 */
	async expandPanel( title: string ) {
		const header = this.panel( title );
		if ( ( await header.getAttribute( 'aria-expanded' ) ) !== 'true' ) {
			await header.click();
		}
	}

	/**
	 * A ToggleControl by its visible label. WP renders these as a real
	 * `<input type="checkbox">` with a linked label, so role + accessible
	 * name is enough -- no CSS class needed the way tab buttons require one.
	 */
	toggle( label: string ): Locator {
		return this.inspector().getByRole( 'checkbox', { name: label, exact: true } );
	}

	/** Sets a ToggleControl to a specific state rather than toggling blind --
	 *  lets a test state the target state instead of counting clicks. */
	async setToggle( label: string, on: boolean ) {
		const checkbox = this.toggle( label );
		if ( ( await checkbox.isChecked() ) !== on ) {
			await checkbox.click();
		}
	}

	/** A SelectControl by its visible label -- Preset, Sticky Position, Scroll
	 *  Target, List Style. WP renders these as a native `<select>`. */
	selectControl( label: string ): Locator {
		return this.inspector().getByRole( 'combobox', { name: label, exact: true } );
	}

	/** A numeric TextControl by its visible label -- currently only Offset
	 *  Top, which sets `type="number"` and so gets the spinbutton role. */
	numberField( label: string ): Locator {
		return this.inspector().getByRole( 'spinbutton', { name: label, exact: true } );
	}

	/** A plain-text field by its visible label -- e.g. Title Text. Renders as
	 *  a contentEditable-backed textbox, not a native `<input>`. */
	textField( label: string ): Locator {
		return this.inspector().getByRole( 'textbox', { name: label, exact: true } );
	}
}
