#!/usr/bin/env node
/**
 * Resolves the plugin build under test and unpacks it to
 * `.plugin-under-test/<block-slug>/`, where `.wp-env.json` (generated by
 * scripts/generate-wp-env.mjs) picks it up.
 *
 * WHY WE TEST A ZIP RATHER THAN THE SOURCE TREE
 * ---------------------------------------------
 * The Table of Contents plugin repo gitignores its `dist/` build output and
 * pulls two submodules from private SSH remotes -- a fresh clone does not
 * even boot. Release zips ship pre-built. Testing the zip sidesteps that
 * entirely and tests the exact artifact users install. This reasoning is not
 * specific to one block, so it is enforced here rather than per-block.
 *
 * BLOCK SELECTION: --block=<slug> or $BLOCK. With one block configured (see
 * blocks/), it's picked automatically.
 *
 * RESOLUTION ORDER for which build to fetch (first match wins)
 *   1. PLUGIN_ZIP      -- local path or URL. Use for release candidates.
 *   2. PLUGIN_VERSION   -- a published wp.org version.
 *   3. (nothing set)    -- latest release, via the wp.org plugin API.
 *
 * Every step validates and reports, so the CI log always states exactly which
 * block and which build was tested. Guessing is never silent.
 */

// Side-effect import: populates process.env from .env.
import './load-env.mjs';

import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { resolveBlockConfig } from './lib/block-config.mjs';

const log = ( label, msg ) => console.log( `[prepare-plugin:${ label }] ${ msg }` );

function fail( label, msg ) {
	console.error( `\n[prepare-plugin:${ label }] FAILED\n\n${ msg }\n` );
	process.exit( 1 );
}

/** Downloads to a temp file and returns its path. */
async function download( label, pluginSlug, url ) {
	log( label, `Downloading ${ url }` );

	const response = await fetch( url, { redirect: 'follow' } );
	if ( ! response.ok ) {
		fail(
			label,
			`Download returned HTTP ${ response.status } for:\n  ${ url }\n\n` +
				`If this is a version number, check it exists on wp.org.`
		);
	}

	const tmp = path.join(
		await fsp.mkdtemp( path.join( os.tmpdir(), 'sbe2e-' ) ),
		`${ pluginSlug }.zip`
	);
	await fsp.writeFile( tmp, Buffer.from( await response.arrayBuffer() ) );
	return tmp;
}

/** Resolves the zip to use, downloading if needed. Returns a local path. */
async function resolveZip( config, root ) {
	const { label, pluginSlug } = config;
	const { PLUGIN_ZIP, PLUGIN_VERSION } = process.env;

	if ( PLUGIN_ZIP ) {
		if ( /^https?:\/\//.test( PLUGIN_ZIP ) ) {
			return { zip: await download( label, pluginSlug, PLUGIN_ZIP ), source: PLUGIN_ZIP };
		}

		// Relative paths resolve against the repo root, not the cwd, so the
		// same value works whether invoked from npm or directly.
		const local = path.resolve( root, PLUGIN_ZIP );
		if ( ! fs.existsSync( local ) ) {
			fail( label, `PLUGIN_ZIP points at a file that does not exist:\n  ${ local }` );
		}
		return { zip: local, source: local };
	}

	if ( PLUGIN_VERSION ) {
		const url = `https://downloads.wordpress.org/plugin/${ pluginSlug }.${ PLUGIN_VERSION }.zip`;
		return { zip: await download( label, pluginSlug, url ), source: url };
	}

	log( label, 'No zip or version specified -- resolving latest from wp.org.' );
	const wpOrgApi = `https://api.wordpress.org/plugins/info/1.0/${ pluginSlug }.json`;
	const info = await fetch( wpOrgApi ).then( ( r ) => r.json() );
	if ( ! info?.download_link ) {
		fail( label, `wp.org API returned no download_link for "${ pluginSlug }".` );
	}
	log( label, `Latest published version is ${ info.version }.` );
	return { zip: await download( label, pluginSlug, info.download_link ), source: info.download_link };
}

/**
 * Reads `Version:` out of the plugin header. This is the single most useful
 * line in the whole CI log -- it is the difference between "the suite passed"
 * and "the suite passed against the build we are about to ship".
 */
async function readPluginVersion( mainPhpPath ) {
	const header = ( await fsp.readFile( mainPhpPath, 'utf8' ) ).slice( 0, 4096 );
	return header.match( /^\s*\*?\s*Version:\s*(.+)$/m )?.[ 1 ].trim() ?? null;
}

async function main() {
	const config = await resolveBlockConfig();
	const { slug, root, pluginSlug } = config;
	const label = slug;

	const { zip, source } = await resolveZip( { ...config, label }, root );

	const destDir = path.join( root, '.plugin-under-test', slug );

	// Always start clean. A stale build left over from a previous run is the
	// exact failure mode this whole script exists to prevent.
	await fsp.rm( destDir, { recursive: true, force: true } );
	await fsp.mkdir( destDir, { recursive: true } );

	log( label, `Unpacking into ${ path.relative( root, destDir ) }/` );
	try {
		execFileSync( 'unzip', [ '-q', zip, '-d', destDir ], { stdio: 'inherit' } );
	} catch {
		fail( label, `Could not unzip:\n  ${ zip }\n\nIs it a valid zip archive?` );
	}

	// --- Validation gate -------------------------------------------------
	const pluginDir = path.join( destDir, pluginSlug );
	if ( ! fs.existsSync( pluginDir ) ) {
		const found = ( await fsp.readdir( destDir ) ).join( ', ' ) || '(empty)';
		fail(
			label,
			`Expected the archive to contain a "${ pluginSlug }/" directory.\n` +
				`Found instead: ${ found }`
		);
	}

	const mainPhp = path.join( pluginDir, `${ pluginSlug }.php` );
	if ( ! fs.existsSync( mainPhp ) ) {
		fail( label, `Archive is missing the plugin's main file:\n  ${ pluginSlug }.php` );
	}

	/**
	 * The main PHP file throws on load if this is absent, which surfaces as an
	 * inscrutable WSOD rather than a test failure. Catch it here instead.
	 */
	const assetPhp = path.join( pluginDir, 'dist', 'index.asset.php' );
	if ( ! fs.existsSync( assetPhp ) ) {
		fail(
			label,
			`Archive is missing dist/index.asset.php.\n\n` +
				`This means it is an unbuilt source checkout, not a release build.\n` +
				`The plugin throws on activation without it. Use a release zip.`
		);
	}

	const version = await readPluginVersion( mainPhp );
	if ( ! version ) {
		fail( label, `Could not parse a "Version:" header from ${ pluginSlug }.php.` );
	}

	log( label, '' );
	log( label, `  Block             : ${ config.displayName } (${ slug })` );
	log( label, `  Plugin under test : ${ pluginSlug }` );
	log( label, `  Version           : ${ version }` );
	log( label, `  Source            : ${ source }` );
	log( label, '' );
	log( label, 'OK.' );

	// A debugging artifact: "we unpacked X but the site reports Y active" is a
	// real failure mode (activation error) that this catches when compared
	// against verify-environment.mjs's environment.json.
	const artifactsDir = process.env.WP_ARTIFACTS_PATH || path.join( root, 'artifacts' );
	await fsp.mkdir( artifactsDir, { recursive: true } );
	await fsp.writeFile(
		path.join( artifactsDir, `plugin-under-test.${ slug }.json` ),
		JSON.stringify( { slug, pluginSlug, version, source }, null, 2 )
	);
}

main().catch( ( error ) => fail( 'error', error.stack || error.message ) );
